#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Register HD Path
      shell: 'cat /var/plexguide/server.hd.path'
      register: hdpath

    - name: Register UNIONFS PATH
      shell: "cat /var/plexguide/unionfs.pgpath"
      register: unionfs_path

    - name: Install UNIONFS Service
      template:
        src: /opt/pgclone/templates/bunionfs.service
        dest: /etc/systemd/system/unionfs.service
        force: yes

    - name: Daemon-Reload
      systemd: state=stopped name=unionfs daemon_reload=yes enabled=no

    - name: Start UnionFS
      systemd: state=started name=unionfs enabled=yes
