#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Stopping Existing GCrypt Service
      systemd:
        daemon_reload: yes
        enabled: no
        state: stopped
        name: gcrypt

    - name: Install GCrypt Service
      template:
        src: /opt/pgclone/templates/gcrypt.service
        dest: /etc/systemd/system/gcrypt.service
        force: yes

    - name: Reload GCrypt Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: gcrypt
