#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install GDRIVE Service
      template:
        src: /opt/pgclone/templates/gdrive.service
        dest: /etc/systemd/system/gdrive.service
        force: yes
      ignore_errors: yes

    - name: Reload GDRIVE Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: gdrive

    - name: Create GDRIVE Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - /mnt/gdrive