#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install TCrypt Service
      template:
        src: /opt/pgclone/templates/tcrypt.service
        dest: /etc/systemd/system/tcrypt.service
        force: yes

    - name: Reload TCrypt Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: tcrypt


    - name: Create TCrypt Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - /mnt/tcrypt
