#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Stopping Existing TCrypt Service
      systemd:
        daemon_reload: yes
        enabled: no
        state: stopped
        name: tcrypt

    - name: Install TCrypt Service
      template:
        src: /opt/pgclone/templates/tcrypt.service
        dest: /etc/systemd/system/tcrypt.service
        force: yes

    - name: Reload TCrypt Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: tcrypt