#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Stopping Existing TDRIVE Service
      systemd:
        daemon_reload: yes
        enabled: no
        state: stopped
        name: tdrive

    - name: Install TDRIVE Service
      template:
        src: /opt/pgclone/templates/tdrive.service
        dest: /etc/systemd/system/tdrive.service
        force: yes
      ignore_errors: yes

    - name: Reload TDRIVE Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: tdrive