#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
# NOTE: UnionFS does not mean 'unionfs', we keep using 'unionfs' for backward compat but have switched to rclone union.
---

- hosts: localhost
  sudo: yes
  tasks:
    - name: Check if mergerfs is installed
      shell: dpkg-query -W -f='${Status}' mergerfs | grep 'install ok installed'
      register: is_installed
      failed_when: no
      changed_when: no

    - name: Update mergerfs only if installed
      get_url: url=https://github.com/trapexit/mergerfs/releases/download/2.25.1/mergerfs_2.25.1.ubuntu-bionic_amd64.deb dest=/tmp/mergerfs.deb
      apt:
        deb: /tmp/mergerfs.deb
      when: is_installed.rc == 0

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register HD Path
      shell: 'cat /var/plexguide/server.hd.path'
      register: hdpath

    - name: Transport Type
      shell: 'cat /var/plexguide/pgclone.transport'
      register: transport55

    - name: Line Remover
      shell: 'sed -i -e "/\[unionfs\]/,+2d" /opt/appdata/plexguide/rclone.conf'

    - name: 'If Fact Matches - Encrypted Blitz'
      set_fact:
        path: 'remotes = gdrive: tdrive: gcrypt: tcrypt: {{hdpath.stdout}}/move'
      when: transport55.stdout == "eblitz"

    - name: 'If Fact Matches - Encrypted Move'
      set_fact:
        path: 'remotes = gdrive: gcrypt: {{hdpath.stdout}}/move'
      when: transport55.stdout == "emove"

    - name: 'If Fact Matches - UnEncrypted Blitz'
      set_fact:
        path: 'remotes = gdrive: tdrive: {{hdpath.stdout}}/move'
      when: transport55.stdout == "ublitz"

    - name: 'If Fact Matches - UnEncrypted Move'
      set_fact:
        path: 'remotes = gdrive: {{hdpath.stdout}}/move'
      when: transport55.stdout == "umove"

    - name: Transport Type
      shell: 'echo "" >> /opt/appdata/plexguide/rclone.conf'
    #      register: transport

    - name: Transport Type
      shell: |
        echo "[unionfs]" >> /opt/appdata/plexguide/rclone.conf
        echo "type = union" >> /opt/appdata/plexguide/rclone.conf
        echo "{{path}}" >> /opt/appdata/plexguide/rclone.conf
    #      register: transport

    - name: 'PG Blitz Execution'
      block:
        - name: Bandwidth Limit
          shell: 'cat /var/plexguide/blitz.bw'
          register: bandwidth

        - name: Install PG Blitz Script
          template:
            src: /opt/pgclone/templates/pgblitz.sh
            dest: /opt/appdata/pgblitz/pgblitz.sh
            force: yes

        - name: Install PG Blitz Service
          template:
            src: /opt/pgclone/templates/pgblitz.service
            dest: /etc/systemd/system/pgblitz.service
            force: yes

        - name: Reload PG Blitz Service
          systemd:
            daemon_reload: yes
            enabled: yes
            state: reloaded
            name: pgblitz

      when: (transport55.stdout == "eblitz") or
        (transport55.stdout == "ublitz")

    - name: 'PG Move Execution'
      block:
        - name: Bandwidth Limit
          shell: 'cat /var/plexguide/move.bw'
          register: bandwidth

        - name: Deploy Version
          shell: 'cat /var/plexguide/rclone/deploy.version'
          register: ver

        - name: Register HD Path
          shell: 'cat /var/plexguide/server.hd.path'
          register: hdpath

        - name: Install MOVE Service
          template:
            src: /opt/pgclone/templates/move_script.sh
            dest: /opt/appdata/plexguide/move.sh
            force: yes

        - name: Install MOVE Service
          template:
            src: /opt/pgclone/templates/move.service
            dest: /etc/systemd/system/move.service
            force: yes

        - name: Reload MOVE Service
          systemd:
            daemon_reload: yes
            enabled: yes
            state: reloaded
            name: move

      when: (transport55.stdout == "emove") or
        (transport55.stdout == "umove")

    - name: Install UNIONFS Service
      template:
        src: /opt/pgclone/templates/unionfs.service
        dest: /etc/systemd/system/unionfs.service
        force: yes

    - name: Reload UNIONFS Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: unionfs
