#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Register HD Path
      shell: "cat /var/plexguide/server.hd.path"
      register: hdpath

    - name: Transport Type
      shell: "cat /var/plexguide/pgclone.transport"
      register: transport

    - name: 'If Fact Matches - Encrypted Blitz'
      set_fact:
        path: 'remote = gdrive: tdrive: gcrypt: tcrypt: {{hdpaths.stdout}}/move'
      when: 'transport.stdout == eblitz'

    - name: 'If Fact Matches - Encrypted Move'
      set_fact:
        path: 'remote = gdrive: gcrypt: {{hdpaths.stdout}}/move'
      when: 'transport.stdout == emove'

    - name: 'If Fact Matches - UnEncrypted Blitz'
      set_fact:
        path: 'remote = gdrive: tdrive: {{hdpaths.stdout}}/move'
      when: 'transport.stdout == ublitz'

    - name: 'If Fact Matches - UnEncrypted Move'
      set_fact:
        path: 'remote = gdrive: {{hdpaths.stdout}}/move'
      when: 'transport.stdout == umove'

    - name: Transport Type
      shell: "echo -e "\n[union]\ntype = union\n{{path}}" >> /opt/appdata/plexguide/rclone.conf"
      register: transport

    - name: Install pgblitz script
      template:
        src: /opt/pgclone/templates/pgblitz.sh
        dest: /opt/appdata/pgblitz/pgblitz.sh
        force: yes

    - name: Install pgblitz Service
      template:
        src: /opt/pgclone/templates/pgblitz.service
        dest: /etc/systemd/system/pgblitz.service
        force: yes

    - name: Enable pgblitz Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: pgblitz
